version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
          paths:
            - .devops-aws-demo/bin
      - python/install-deps
      - python/save-cache
      - run:
          name: Run Tests
          command: |
            . .devops-aws-demo/bin/activate
            make test
        

workflows:
  main:
    jobs:
      - build-and-test
