version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps:
          dependency-file: requirements.txt
      - python/save-cache
      - run:
          name: Run
          command: |
            python hello.py
  reset:
    executor: python/default
    steps:
      - python/uninstall-deps:
          requirements-file: ./requirements.txt
        

workflows:
  main:
    jobs:
      - reset
      - build-and-test

