version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps:
          dependency-file: ./devops-aws-demo/requirements.txt
      - python/save-cache
      - run:
          name: Run
          command: |
            python hello.py
        
workflows:
  main:
    jobs:
      - build-and-test

