version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache:
           key: pip2
      - python/install-deps
      - python/save-cache:
           key: pip2
      - run:
          name: Run Tests
          command: |
             make test
      - run:
          name: Run Lint
          command: |
             make lint


workflows:
  main:
    jobs:
      - build-and-test

