version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps:
           local: false
      - python/save-cache
      - run:
          name: Run Tests
          command: |
             pytest test_hello.py


workflows:
  main:
    jobs:
      - build-and-test

